/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
    "./public/**/*.html",
    "./css/**/*.css",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#22a7d0',
      },
    },
  },
  safelist: [
    // Common layout utilities
    'container',
    'mx-auto',
    'px-4',
    'px-6',
    'py-2',
    'py-3',
    'py-4',
    'py-6',
    'py-8',
    'py-10',
    'py-12',
    'py-16',
    'py-20',
    'py-32',
    // Common text utilities
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    // Common spacing
    'mt-1',
    'mt-2',
    'mt-4',
    'mt-6',
    'mt-8',
    'mt-10',
    'mt-12',
    'mb-2',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-12',
    'mr-2',
    'mr-3',
    'mr-4',
    'ml-2',
    'ml-3',
    'ml-4',
    // Grid and Flexbox
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'gap-4',
    'gap-6',
    'gap-8',
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'justify-between',
    'space-x-1',
    'space-x-2',
    'space-x-4',
    'space-y-4',
    // Common colors
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'bg-gray-500',
    'bg-gray-600',
    'bg-gray-700',
    'bg-gray-800',
    'bg-gray-900',
    'text-white',
    'text-gray-300',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-gray-900',
    // Borders and Radius
    'border',
    'border-2',
    'border-gray-200',
    'border-gray-300',
    'border-gray-700',
    'rounded',
    'rounded-lg',
    'rounded-full',
    // Shadows
    'shadow',
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    // Display and Position
    'hidden',
    'block',
    'inline-block',
    'md:flex',
    'md:hidden',
    'md:block',
    'fixed',
    'sticky',
    'relative',
    'absolute',
    'top-0',
    'z-50',
    // Widths and Heights
    'w-4',
    'w-5',
    'w-6',
    'w-8',
    'w-16',
    'w-24',
    'w-32',
    'w-full',
    'h-4',
    'h-5',
    'h-6',
    'h-8',
    'h-16',
    'h-24',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-6xl',
    'max-w-7xl',
    // Hover states
    'hover:bg-gray-50',
    'hover:bg-gray-700',
    'hover:text-white',
    'hover:bg-[#1e96bc]',
    'hover:bg-[#22a7d0]',
    // Transitions
    'transition',
    'transition-all',
    'transition-colors',
    'duration-200',
    'duration-300',
    // Opacity
    'opacity-0',
    'opacity-75',
    'opacity-100',
    // Backdrop
    'backdrop-blur-md',
    'bg-opacity-50',
    // Text alignment
    'text-center',
    'text-left',
    'text-right',
    // Misc
    'leading-tight',
    'overflow-hidden',
    'overflow-y-auto',
    'animate-pulse',
  ],
  plugins: [],
}
